# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Go CI Pipeline

# Pemicu (Triggers)
on:
  push:
    branches:
    - main
    - develop
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
  pull_request:
    branches:
    - main
    - develop

jobs:
  # Nama job ini akan digunakan di Branch Protection Rules.
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: go mod download

    - name: Run Linter
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Run Unit Tests with Coverage
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
    # - name: Upload Coverage Report
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }} # Token opsional untuk repo privat
    #     files: ./coverage.out
    #     fail_ci_if_error: true
